/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsIdRouteImport } from './routes/apps.$id'
import { Route as AppsIdGateRouteImport } from './routes/apps.$id_.gate'
import { Route as AppsIdAuditRouteImport } from './routes/apps.$id_.audit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIdRoute = AppsIdRouteImport.update({
  id: '/apps/$id',
  path: '/apps/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIdGateRoute = AppsIdGateRouteImport.update({
  id: '/apps/$id_/gate',
  path: '/apps/$id/gate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIdAuditRoute = AppsIdAuditRouteImport.update({
  id: '/apps/$id_/audit',
  path: '/apps/$id/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/$id': typeof AppsIdRoute
  '/apps/$id/audit': typeof AppsIdAuditRoute
  '/apps/$id/gate': typeof AppsIdGateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/$id': typeof AppsIdRoute
  '/apps/$id/audit': typeof AppsIdAuditRoute
  '/apps/$id/gate': typeof AppsIdGateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/$id': typeof AppsIdRoute
  '/apps/$id_/audit': typeof AppsIdAuditRoute
  '/apps/$id_/gate': typeof AppsIdGateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apps/$id' | '/apps/$id/audit' | '/apps/$id/gate'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apps/$id' | '/apps/$id/audit' | '/apps/$id/gate'
  id: '__root__' | '/' | '/apps/$id' | '/apps/$id_/audit' | '/apps/$id_/gate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsIdRoute: typeof AppsIdRoute
  AppsIdAuditRoute: typeof AppsIdAuditRoute
  AppsIdGateRoute: typeof AppsIdGateRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$id': {
      id: '/apps/$id'
      path: '/apps/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof AppsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$id_/gate': {
      id: '/apps/$id_/gate'
      path: '/apps/$id/gate'
      fullPath: '/apps/$id/gate'
      preLoaderRoute: typeof AppsIdGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$id_/audit': {
      id: '/apps/$id_/audit'
      path: '/apps/$id/audit'
      fullPath: '/apps/$id/audit'
      preLoaderRoute: typeof AppsIdAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsIdRoute: AppsIdRoute,
  AppsIdAuditRoute: AppsIdAuditRoute,
  AppsIdGateRoute: AppsIdGateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
